### ISSUE TITLE
Recipe app

### ISSUE THREAD

**Issue by sentayhu19** [sentayhu19/Recipe-app#15]
Recipe app: Group project 

[**Project Link**](https://github.com/sentayhu19/Recipe-app/projects/1)

Members (2)

- @kosher9: Cédric Kossi 
- @sentayhu19 :Sentayhu Berhanu

**Comment by hiromataba** [comment]
# Status: Approved :tada: :tada: :tada: 
Hi @sentayhu19 and @kosher9     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
